name: grid2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.11=h7f8727e_2
  - pip=23.3=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.8.6
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.13.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - black==23.10.1
      - bleach==6.1.0
      - blessed==1.20.0
      - cachetools==5.3.2
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.1
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorful==0.5.5
      - comm==0.1.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepdiff==6.6.1
      - defusedxml==0.7.1
      - distlib==0.3.7
      - dm-tree==0.1.8
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - farama-notifications==0.0.4
      - fastjsonschema==2.18.1
      - filelock==3.12.4
      - fonttools==4.43.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - google-api-core==2.12.0
      - google-auth==2.23.3
      - google-auth-oauthlib==1.1.0
      - googleapis-common-protos==1.61.0
      - gpustat==1.1.1
      - gputil==1.4.0
      - grid2op==1.9.4
      - grpcio==1.59.0
      - gymnasium==0.28.1
      - idna==3.4
      - imageio==2.31.6
      - iniconfig==2.0.0
      - ipykernel==6.26.0
      - ipython==8.16.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jax-jumpy==1.0.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.5.0
      - jupyter-console==6.6.3
      - jupyter-core==5.4.0
      - jupyter-events==0.8.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.9.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.7
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - jyquickhelper==0.4.220
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightsim2grid==0.7.5
      - llvmlite==0.39.1
      - lz4==4.3.2
      - markdown==3.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==3.0.2
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.2
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numba==0.56.4
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.108
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.52
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencensus==0.11.3
      - opencensus-context==0.1.3
      - opencv-python==4.8.1.78
      - ordered-set==4.1.0
      - overrides==7.4.0
      - packaging==23.2
      - pandapower==2.13.1
      - pandas==2.1.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.11.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - platformdirs==3.11.0
      - plotly==5.18.0
      - pluggy==1.3.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.23.4
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-spy==0.3.14
      - pyarrow==13.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==1.10.13
      - pygifsicle==1.0.7
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pytest==7.4.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.1
      - ray==2.7.1
      - referencing==0.30.2
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.6.0
      - rpds-py==0.10.6
      - rsa==4.9
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - seaborn==0.13.0
      - send2trash==1.8.2
      - six==1.16.0
      - smart-open==6.4.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - support-developer==1.0.5
      - sympy==1.12
      - tenacity==8.2.3
      - tensorboard==2.15.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==2.1.0
      - torch-geometric==2.4.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.12.0
      - triton==2.1.0
      - typer==0.9.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.0.7
      - virtualenv==20.21.0
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - yarl==1.9.2
prefix: /home/scheschb/miniconda3/envs/grid2
